/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;
import javax.swing.ImageIcon;
/**
 *
 * @author paulo
 */
public class BrawlStats extends javax.swing.JFrame {
    
    String display;
    
    /**
     * Creates new form BrawlStats
     */
    public BrawlStats() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selecMain = new javax.swing.JComboBox<>();
        imgBrawler = new javax.swing.JLabel();
        imgEngP = new javax.swing.JLabel();
        imgEngS = new javax.swing.JLabel();
        imgStar = new javax.swing.JLabel();
        imgMode = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        imgGad = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtVan = new javax.swing.JTextPane();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guide Stars");
        setIconImage(new ImageIcon(getClass().getResource("/imagens/Logo.png")).getImage());
        getContentPane().setLayout(null);

        selecMain.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selecMain.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Brawler", "Shelly", "Nita", "Colt", "Bull", "Jessie", "Brock", "Dynamike", "Bo", "Tick", "8-BIT", "EMZ", "Stu", "El Primo", "Barley", "Poco", "Rosa", "Rico", "Darryl", "Penny", "Carl", "Jacky", "Piper", "Pam", "Frank", "Bibi", "Bea", "Nani", "Edgar", "Griff", "Grom", "Bonnie", "Mortis", "Tara", "Eugênio", "Max", "Mister P", "Sprout", "Byron", "Squeak", "Spike", "Corvo", "Leon", "Sandy", "Amber", "Meg", "Gale", "Wattson", "Colette", "Lou", "Coronel Ruffs", "Belle", "Buzz", "Ash", "Lola", "Fang", "Eve", "Janet" }));
        selecMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecMainMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                selecMainMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                selecMainMouseReleased(evt);
            }
        });
        selecMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecMainActionPerformed(evt);
            }
        });
        getContentPane().add(selecMain);
        selecMain.setBounds(6, 6, 145, 22);

        imgBrawler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Nada.png"))); // NOI18N
        getContentPane().add(imgBrawler);
        imgBrawler.setBounds(6, 34, 150, 150);

        imgEngP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        imgEngP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/MiniNada.png"))); // NOI18N
        getContentPane().add(imgEngP);
        imgEngP.setBounds(278, 34, 60, 60);

        imgEngS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        imgEngS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/MiniNada.png"))); // NOI18N
        getContentPane().add(imgEngS);
        imgEngS.setBounds(278, 122, 60, 62);

        imgStar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        imgStar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/MiniNada.png"))); // NOI18N
        getContentPane().add(imgStar);
        imgStar.setBounds(174, 34, 60, 60);

        imgMode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        imgMode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/MiniNada.png"))); // NOI18N
        getContentPane().add(imgMode);
        imgMode.setBounds(220, 210, 60, 60);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Engrenagem secundária");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(243, 100, 132, 16);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Poder de Estrela |");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 9, 97, 16);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Acessório  |");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(174, 100, 63, 16);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Engrenagem primária");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(263, 9, 119, 16);

        imgGad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        imgGad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/MiniNada.png"))); // NOI18N
        getContentPane().add(imgGad);
        imgGad.setBounds(174, 122, 60, 60);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Modo de Jogo");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(213, 188, 78, 16);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Vantagens:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 190, 69, 16);

        txtVan.setText("- ??????\n- ??????\n- ??????\n- ??????");
        jScrollPane1.setViewportView(txtVan);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(6, 212, 150, 58);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 0, 0, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Background.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -40, 410, 330);

        setSize(new java.awt.Dimension(404, 321));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void selecMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecMainMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_selecMainMouseClicked

    private void selecMainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecMainMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecMainMousePressed

    private void selecMainMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecMainMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_selecMainMouseReleased
  
    private void selecMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecMainActionPerformed
        // TODO add your handling code here:
        display = selecMain.getSelectedItem().toString();
        switch (display) {
            case "Shelly":
                imgShelly();
                break;
            case "Nita":
                imgNita();
                break;
            case "Colt":
                imgColt();
                break;
            case "Bull":
                imgBull();
                break;
            case "Jessie":
                imgJessie();
                break;
            case "Brock":
                imgBrock();
                break;
            case "Dynamike":
                imgDynamike();
                break;
            case "Bo":
                imgBo();
                break;
            case "Tick":
                imgTick();
                break;
            case "8-BIT":
                imgBIT();
                break;
            case "EMZ":
                imgEMZ();
                break;
            case "Stu":
                imgStu();
                break;
            case "El Primo":
                imgElPrimo();
                break;
            case "Barley":
                imgBarley();
                break;
            case "Poco":
                imgPoco();
                break;
            case "Rosa":
                imgRosa();
                break;
            case "Rico":
                imgRico();
                break;
            case "Darryl":
                imgDarryl();
                break;
            case "Penny":
                imgPenny();
                break;
            case "Carl":
                imgCarl();
                break;
            case "Jacky":
                imgJacky();
                break;
            case "Piper":
                imgPiper();
                break;
            case "Pam":
                imgPam();
                break;
            case "Frank":
                imgFrank();
                break;
            case "Bibi":
                imgBibi();
                break;
            case "Bea":
                imgBea();
                break;
            case "Nani":
                imgNani();
                break;
            case "Edgar":
                imgEdgar();
                break;
            case "Griff":
                imgGriff();
                break;
            case "Grom":
                imgGrom();
                break;
            case "Mortis":
                imgMortis();
                break;
            case "Tara":
                imgTara();
                break;
            case "Eugênio":
                imgEugenio();
                break;
            case "Max":
                imgMax();
                break;
            case "Mister P":
                imgMisterP();
                break;
            case "Sprout":
                imgSprout();
                break;
            case "Byron":
                imgByron();
                break;
            case "Squeak":
                imgSqueak();
                break;
            case "Spike":
                imgSpike();
                break;
            case "Corvo":
                imgCorvo();
                break;
            case "Leon":
                imgLeon();
                break;
            case "Sandy":
                imgSandy();
                break;
            case "Amber":
                imgAmber();
                break;
            case "Meg":
                imgMeg();
                break;
            case "Gale":
                imgGale();
                break;
            case "Wattson":
                imgWattson();
                break;
            case "Colette":
                imgColette();
                break;
            case "Lou":
                imgLou();
                break;
            case "Coronel Ruffs":
                imgRuffs();
                break;
            case "Belle":
                imgBelle();
                break;
            case "Buzz":
                imgBuzz();
                break;
            case "Ash":
                imgAsh();
                break;
            case "Lola":
                imgLola();
                break;
            case "Fang":
                imgFang();
                break;
            case "Eve":
                imgEve();
                break;
            case "Janet":
                imgJanet();
                break;
            case "Bonnie":
                imgBonnie();
                break;
            case "Selecione o Brawler":
                imgNada();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_selecMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrawlStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrawlStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrawlStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrawlStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrawlStats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgBrawler;
    private javax.swing.JLabel imgEngP;
    private javax.swing.JLabel imgEngS;
    private javax.swing.JLabel imgGad;
    private javax.swing.JLabel imgMode;
    private javax.swing.JLabel imgStar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> selecMain;
    private javax.swing.JTextPane txtVan;
    // End of variables declaration//GEN-END:variables
  
    private void imgShelly(){
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Shelly.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spShelly.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acShelly.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Invasão.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Recupera\u00e7\u00e3o
                       - Alcance
                       - Perman\u00eancia
                       - Dano""");
    }
    
    private void imgNita() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Nita.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spNita.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acNita.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Regeneração.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Roubo.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Dano ao Cofre
                       - Perman\u00eancia do Urso
                       - Perman\u00eancia
                       - Regenera\u00e7\u00e3o""");
    }

    private void imgColt() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Colt.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spColt.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acColt.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Roubo.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Alcance
                       - Press\u00e3o
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgBull() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Bull.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spBull.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acBull.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Regeneração.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Roubo.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Press\u00e3o
                       - Recupera\u00e7\u00e3o
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgJessie() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Jessie.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spJessie.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acJessie.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Regeneração.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Roubo.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - \u00c1rea de Efeito
                       - Press\u00e3o
                       - Perman\u00eancia
                       - Regenera\u00e7\u00e3o""");
    }

    private void imgBrock() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Brock.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spBrock.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acBrock.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Nocaute.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Press\u00e3o
                       - Evas\u00e3o e Movimenta\u00e7\u00e3o
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgDynamike() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Dynamike.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spDynamike.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acDynamike.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/ZonaSegura.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Dano da Ult
                       - Controle de grupo
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgBo() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Bo.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spBo.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acBo.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/CaçaEstrela.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Controle de grupo
                       - Recarga da Ult
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgTick() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Tick.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spTick.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acTick.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Regeneração.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Nocaute.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Recarga
                       - Prote\u00e7\u00e3o
                       - Perman\u00eancia
                       - Regenera\u00e7\u00e3o""");
    }

    private void imgBIT() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/8-Bit.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/sp8-BIT.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/ac8-BIT.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Velocidade.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Roubo.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Dano e \u00c1rea da Ult
                       - Press\u00e3o
                       - Dano
                       - Velocidade""");
    }

    private void imgEMZ() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/EMZ.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spEMZ.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acEMZ.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Exterminio.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Dano
                       - Press\u00e3o
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgStu() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Stu.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spStu.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acStu.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Resistencia.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/FuteBrawl.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Movimenta\u00e7\u00e3o
                       - Velocidade
                       - Perman\u00eancia
                       - Resist\u00eancia""");
    }

    private void imgElPrimo() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/El Primo.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spElPrimo.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acElPrimo.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Regeneração.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Combate.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Dano cont\u00ednuo
                       - Press\u00e3o
                       - Regenera\u00e7\u00e3o
                       - Dano""");
    }

    private void imgBarley() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Barley.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spBarley.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acBarley.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Roubo.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Dano por segundo
                       - Regenera\u00e7\u00e3o
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgPoco() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Poco.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spPoco.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acPoco.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Regeneração.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/PiqueGema.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Cura aos aliados
                       - Cura
                       - Perman\u00eania
                       - Regenera\u00e7\u00e3o""");
    }

    private void imgRosa() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Rosa.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spRosa.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acRosa.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Resistencia.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/FuteBrawl.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Recuperação
                       - Vis\u00e3o / Controle de grupo
                       - Dano
                       - Resist\u00eancia""");
    }

    private void imgRico() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Rico.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spRico.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acRico.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Regeneração.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/ZonaSegura.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Movimenta\u00e7\u00e3o
                       - Cura
                       - Perman\u00eancia
                       - Regenera\u00e7\u00e3o""");
    }

    private void imgDarryl() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Darryl.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spDarryl.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acDarryl.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Regeneração.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Roubo.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Press\u00e3o
                       - Press\u00e3o
                       - Dano
                       - Regenera\u00e7\u00e3o""");
    }

    private void imgPenny() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Penny.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spPenny.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acPenny.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Regeneração.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Roubo.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Press\u00e3o pelo canh\u00e3o
                       - Press\u00e3o
                       - Perman\u00eancia
                       - Regenera\u00e7\u00e3o""");
    }

    private void imgCarl() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Carl.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spCarl.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acCarl.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Regeneração.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/PiqueGema.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Seguran\u00e7a
                       - Movimenta\u00e7\u00e3o
                       - Regenera\u00e7\u00e3o
                       - Press\u00e3o""");
    }

    private void imgJacky() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Jacky.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spJacky.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acJacky.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Resistencia.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Regeneração.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/FuteBrawl.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Seguran\u00e7a
                       - Movimenta\u00e7\u00e3o
                       - Resist\u00eancia
                       - Regenera\u00e7\u00e3o""");
    }

    private void imgPiper() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Piper.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spPiper.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acPiper.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Nocaute.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Dano
                       - Chance de acerto
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgPam() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Pam.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spPam.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acPam.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Regeneração.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/ZonaSegura.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Cura do grupo
                       - Recupera\u00e7\u00e3o
                       - Regenera\u00e7\u00e3o
                       - Dano""");
    }

    private void imgFrank() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Frank.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spFrank.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acFrank.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Resistencia.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Regeneração.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/FuteBrawl.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Seguran\u00e7a
                       - Contra CG
                       - Resist\u00eancia
                       - Regenera\u00e7\u00e3o""");
    }

    private void imgBibi() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Bibi.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spBibi.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acBibi.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Resistencia.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Regeneração.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/FuteBrawl.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Movimenta\u00e7\u00e3o
                       - Recupera\u00e7\u00e3o
                       - Resist\u00eancia
                       - Regenera\u00e7\u00e3o""");
    }

    private void imgBea() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Bea.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spBea.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acBea.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Nocaute.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Segunda chance
                       - Controle de grupo / Barreira
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgNani() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Nani.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spNani.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acNani.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Nocaute.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Dano seguro
                       - Prote\u00e7\u00e3o
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgEdgar() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Edgar.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spEdgar.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acEdgar.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Combate.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Dano ao Ultar
                       - Seguran\u00e7a
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgGriff() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Griff.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spGriff.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acGriff.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Regeneração.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/BasqueteBrawl.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Press\u00e3o
                       - Limpeza de mapa / Fulga
                       - Perman\u00eancia
                       - Regenera\u00e7\u00e3o""");
    }

    private void imgGrom() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Grom.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spGrom.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acGrom.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Nocaute.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Dano da Ult
                       - Press\u00e3o
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgMortis() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Mortis.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spMortis.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acMortis.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Resistencia.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/FuteBrawl.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Alcance
                       - Movimenta\u00e7\u00e3o
                       - Dano
                       - Resist\u00eancia""");
    }

    private void imgTara() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Tara.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spTara.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acTara.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/PiqueGema.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Recupera\u00e7\u00e3o
                       - Distra\u00e7\u00e3o
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgEugenio() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Eugenio.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spEugenio.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acEugenio.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Nocaute.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Dano
                       - Fuga / Recupera\u00e7\u00e3o
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgMax() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Max.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spMax.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acMax.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/BasqueteBrawl.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Press\u00e3o
                       - Avan\u00e7o seguro
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgMisterP() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/MisterP.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spMisterP.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acMisterP.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Nocaute.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Dano e \u00c1rea da Ult
                       - Press\u00e3o
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgSprout() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Sprout.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spSprout.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acSprout.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Nocaute.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - \u00c1rea do ataque
                       - Barreira
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgByron() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Byron.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spByron.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acByron.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Nocaute.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Taxa de aceto
                       - Press\u00e3o
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgSqueak() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Squeak.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spSqueak.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acSqueak.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/CaçaEstrela.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Controle de grupo
                       - Vis\u00e3o / Controle de grupo
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgSpike() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Spike.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spSpike.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acSpike.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Regeneração.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/ZonaSegura.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Taxa de acerto
                       - Barreira / Recupera\u00e7\u00e3o
                       - Perman\u00eancia
                       - Regenera\u00e7\u00e3o""");
    }

    private void imgCorvo() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Corvo.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spCorvo.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acCorvo.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Combate.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Letalidade
                       - Seguran\u00e7a
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgLeon() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Leon.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spLeon.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acLeon.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/ZonaSegura.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Movimenta\u00e7\u00e3o
                       - Apreens\u00e3o
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgSandy() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Sandy.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spSandy.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acSandy.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Regeneração.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/ZonaSegura.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Recupera\u00e7\u00e3o
                       - Controle de grupo
                       - Perman\u00eancia
                       - Regenera\u00e7\u00e3o""");
    }

    private void imgAmber() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Amber.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spAmber.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acAmber.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Regeneração.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/ZonaSegura.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Press\u00e3o
                       - Movimenta\u00e7\u00e3o
                       - Perman\u00eancia
                       - Regenera\u00e7\u00e3o""");
    }

    private void imgMeg() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Meg.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spMeg.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acMeg.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Regeneração.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/ZonaSegura.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Dano / Controle da \u00e1rea
                       - Press\u00e3o do time
                       - Perman\u00eancia
                       - Regenera\u00e7\u00e3o""");
    }

    private void imgGale() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Gale.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spGale.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acGale.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Resistencia.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/BasqueteBrawl.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Dificulta avan\u00e7o
                       - Impede avan\u00e7o
                       - Perman\u00eancia
                       - Resist\u00eancia""");
    }

    private void imgWattson() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Wattson.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spWattson.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acWattson.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Combate.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Dano e \u00c1rea da Ult
                       - Press\u00e3o
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgColette() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Colette.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spColette.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acColette.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Resistencia.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/BasqueteBrawl.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Impede avan\u00e7o
                       - Dano
                       - Perman\u00eancia
                       - Resist\u00eancia""");
    }

    private void imgLou() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Lou.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spLou.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acLou.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Combate.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Dificulta ataque
                       - Seguran\u00e7a
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgRuffs() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Ruffs.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spRuffs.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acRuffs.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Exterminio.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Dano / Abertura de mapa
                       - Barreira
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgBelle() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Belle.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spBelle.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acBelle.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Nocaute.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Prote\u00e7\u00e3o
                       - Controle de grupo / Fulga
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgBuzz() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Buzz.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spBuzz.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acBuzz.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Combate.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Controle de grupo
                       - Bote / Fulga
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgAsh() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Ash.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spAsh.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acAsh.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Resistencia.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/FuteBrawl.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Press\u00e3o
                       - Recupera\u00e7\u00e3o
                       - Resist\u00eancia
                       - Dano""");
    }

    private void imgLola() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Lola.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spLola.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acLola.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/PiqueGema.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Recupera\u00e7\u00e3o aliada
                       - Fulga e Recupera\u00e7\u00e3o
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgFang() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Fang.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spFang.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acFang.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Resistencia.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/BasqueteBrawl.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Exterm\u00ednio / Fulga
                       - Controle de grupo
                       - Resist\u00eancia
                       - Dano""");
    }

    private void imgEve() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Eve.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spEve.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acEve.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/CaçaEstrela.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Distra\u00e7\u00e3o / Dano por segundo
                       - Fulga / Avan\u00e7o
                       - Perman\u00eancia
                       - Dano""");
    }

    private void imgJanet() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Janet.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spJanet.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acJanet.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Escudo.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/ZonaSegura.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Maior alcance mais r\u00e1pido
                       - Dano por segundo / Vis\u00e3o
                       - Perman\u00eancia
                       - Dano""");
    }
    
    private void imgBonnie() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Bonnie.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/spBonnie.png"));
        imgStar.setIcon(img02);
        ImageIcon img03 = new ImageIcon(getClass().getResource("/imagens/acBonnie.png"));
        imgGad.setIcon(img03);
        ImageIcon img04 = new ImageIcon(getClass().getResource("/imagens/Força.png"));
        imgEngP.setIcon(img04);
        ImageIcon img05 = new ImageIcon(getClass().getResource("/imagens/Regeneração.png"));
        imgEngS.setIcon(img05);
        ImageIcon img06 = new ImageIcon(getClass().getResource("/imagens/Combate.png"));
        imgMode.setIcon(img06);
        txtVan.setText("""
                       - Dano
                       - Movimenta\u00e7\u00e3o / Press\u00e3o
                       - Dano
                       - Regenera\u00e7\u00e3o""");
    }
    
    private void imgNada() {
        ImageIcon img01 = new ImageIcon(getClass().getResource("/imagens/Nada.png"));
        imgBrawler.setIcon(img01);
        ImageIcon img02 = new ImageIcon(getClass().getResource("/imagens/MiniNada.png"));
        imgStar.setIcon(img02);
        imgGad.setIcon(img02);
        imgEngP.setIcon(img02);
        imgEngS.setIcon(img02);
        imgMode.setIcon(img02);
        txtVan.setText("""
                       - ??????
                       - ??????
                       - ??????
                       - ??????""");
    }
    
}